#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
from pathlib import Path

from pyspark.sql import SparkSession
from pyspark.sql import functions as F


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Inspect logical partition parquet output")
    parser.add_argument("--run-dir", required=True, help="Run directory generated by logical_partition_job.py")
    parser.add_argument("--top", type=int, default=10, help="Top N rows to show")
    return parser.parse_args()


def main() -> None:
    for key in ("SPARK_HOME", "SPARK_CONF_DIR", "HADOOP_CONF_DIR", "YARN_CONF_DIR"):
        os.environ.pop(key, None)

    args = parse_args()
    run_dir = Path(args.run_dir)
    index_dir = run_dir / "index_parquet"

    if not index_dir.exists():
        raise FileNotFoundError(f"Missing parquet dir: {index_dir}")

    spark = (
        SparkSession.builder.appName("cube-encoder-partition-inspect")
        .master("local[*]")
        .config("spark.hadoop.fs.defaultFS", "file:///")
        .config("spark.eventLog.enabled", "false")
        .getOrCreate()
    )
    df = spark.read.parquet(index_dir.resolve().as_uri())

    total = df.count()
    by_band = df.groupBy("band").agg(F.count(F.lit(1)).alias("cnt")).orderBy(F.col("cnt").desc())
    by_grid = df.groupBy("grid_type", "grid_level").agg(F.count(F.lit(1)).alias("cnt"))

    print(f"run_dir: {run_dir.resolve()}")
    print(f"total_rows: {total}")
    print("rows_by_band:")
    by_band.show(50, truncate=False)
    print("rows_by_grid:")
    by_grid.show(20, truncate=False)
    print("sample:")
    df.select(
        "scene_id",
        "band",
        "space_code",
        "st_code",
        "window_col_off",
        "window_row_off",
        "intersect_min_lon",
        "intersect_min_lat",
        "intersect_max_lon",
        "intersect_max_lat",
        "sample_mean_band1",
    ).show(args.top, truncate=False)

    spark.stop()


if __name__ == "__main__":
    main()
